spring.application.name=shop

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1

spring.datasource.username=shop
spring.datasource.password=shop

mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mappers*.xml

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB

upload.path=C:/upload


kakao.client-id=d5130702ba4c3c0f55cc0ff03e5925f0
kakao.client-secret=NpLtYvQ2lKzvdjo48zHhJZFNHj9QMWEi
kakao.redirect-uri=http://localhost:5173/member/kakao
kakao.token-uri=https://kauth.kakao.com/oauth/token
kakao.user-info-uri=https://kapi.kakao.com/v2/user/me